### ISSUE TITLE
Quickstart's "easy way" description stops too early

### ISSUE THREAD

**Issue by arafalov** [projectblacklight/blacklight#1069]
Following https://github.com/projectblacklight/blacklight/wiki/Quickstart the **easy way** does not actually end up with the example running. One has to also read the **hard way** and do those steps from step 5 (6? 7?).

It would be good to clarify that some of the steps apply to the **easy way** as well. Including that one has to **cd search_app** before running rake commands.

Also, the command to start Jetty is provided. The command to stop Jetty should be mentioned as well and explain that this is to start/stop the Solr server.

**Comment by barmintor** [comment]
The Quickstart guide was updated to try and address these issues. Can you review the new version for clarity?

**Comment by arafalov** [comment]
Looks better. Maybe add at the end of "Easy" something like *continue with the step 6 below* to indicate that we are not completely done here yet.

**Comment by thatandromeda** [comment]
FWIW, I just tried using the quickstart, and it was clear to me that I needed to continue to step 6 from the easy version, but I did not have a functioning Blacklight when I was done; http://localhost:8983/solr/#/blacklight-core/query (as provided in the instructions) yields "HTTP ERROR: 404

Problem accessing /solr/. Reason:

    Not Found
", and ingesting the sample MARC records also fails due to not finding Solr. Is there additional configuration/downloading that needs to be done to make Solr happy?

**Comment by cbeer** [comment]
@thatandromeda can you check which version of `java` you have? I see the quickstart only mentioned 1.6+, but I believe recent versions of Solr require Java 1.7+. Failing that, you may find some clues in  `./jetty/jettywrapper.log`.

**Comment by thatandromeda** [comment]
In fact, I have 1.6.

The log file has various messages consistent with an unsupported version.

**Comment by cbeer** [comment]
Thanks. I've made an issue https://github.com/projecthydra/jettywrapper/issues/43 to try to capture this with a better error message.
