### ISSUE TITLE
HTML 'prefix' attribute on root 'html' element

### ISSUE THREAD

**Issue by mccalluc** [projectblacklight/blacklight#1220]
We would like to add [Open Graph](http://ogp.me/) metadata on our pages. The OG examples and the [HTML+RDFa](http://dev.w3.org/html5/rdfa/) docs suggest that the namespace be defined with a `prefix` attribute on the `<html>` element. (Older docs will say `xmlns` instead.) We can just override all of `app/views/layouts/blacklight.html.erb`, but that is generally not for the best. Would any of these approaches be an acceptable PR?
- Just add the 'og' prefix... but someone will have the same problem with the next namespace they need to add.
- Make a tiny partial just for the prefix attribute value that can be overridden... but then if two gems both add a namespace, one may shadow the other.
- Some new config where namespaces can be defined... but feels like overkill.

(For reference, Sufia is using OG. They define the namespace in their [own layout](https://github.com/projecthydra/sufia/blob/master/app/views/layouts/sufia-one-column.html.erb), though prefix is missing in the two-column layout: that might be a bug for them.)

Thanks for any thoughts.

**Comment by jkeck** [comment]
I think it would make a great addition to have HTML prefixes configurable in Blacklight.  This is undoubtedly something that others could use and other Blacklight plugins could take advantage of if they need to add additional prefixes.

We do something similar for the [`class` attribute of the `body` element](https://github.com/projectblacklight/blacklight/blob/master/app/helpers/blacklight/blacklight_helper_behavior.rb#L70-L83) and perhaps this pattern would be useful for this use-case.

**Comment by mccalluc** [comment]
@jkeck: I've forked and made a branch at https://github.com/mccalluc/blacklight/tree/prefix-attribute. Do you want to check if this is approximately the right direction? I'm gettting a number of errors which I think are unrelated, probably something in my local environment, but I wanted to run this by you sooner rather than later.
```
Failure/Error: sign_in 'user1'
     NoMethodError:
       undefined method `require_no_authentication' for #<Devise::SessionsController:0x007fdea089ee38>
```

**Comment by jkeck** [comment]
Yeah, that looks good.  Just a few minor things on that branch.

We should probably generate the prefix into the application's configuration instead of it being part of the core configuration.  It should probably be commented out or assigned to an empty hash since not everybody will want the OpenGraph prefix in their HTML. Check out Blacklight's [controller generator](https://github.com/projectblacklight/blacklight/blob/master/lib/generators/blacklight/templates/catalog_controller.rb) to see how we generate the configuration into the host app's controller.

When you invoke methods in ruby that do not take any arguments you should not include the empty parenthesis (i.e. `namespace_prefixes()` should be `namespace_prefixes`).  See the 2nd bullet under the syntax section of the [Ruby Style Guide](https://github.com/bbatsov/ruby-style-guide#syntax).

Thanks for working on this!

**Comment by atz** [comment]
PR is merged, closing.
