### ISSUE TITLE
searches posted to Facebook messes up facet params

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#1784]
It looks like they parse the blacklight URL and then re-emit it using their own library that converts facet values from arrays (e.g. `?f[key][]=value`) to hashes (`?f[key][0]=value`)

**Comment by mejackreed** [comment]
Relevant discussion: https://groups.google.com/d/msg/blacklight-development/IZaKsuGExkc/LYSM8LL1BwAJ

And @jronallo solution: https://gist.github.com/jronallo/94ee890a6f040b3d7b3bc41ff788e5ad

**Comment by eldonquijote** [comment]
We've been experiencing the issue described here again with Blacklight 7.0.1 - does the fix described not apply/work anymore?

[https://collections.lib.utexas.edu/?f[mods_relatedItem_titleInfo_title_source_t][0]=Genaro+Garcia%3A+Imprints+and+Images](https://collections.lib.utexas.edu/?f[mods_relatedItem_titleInfo_title_source_t][0]=Genaro+Garcia%3A+Imprints+and+Images)

**Comment by jrochkind** [comment]
I am also experiencing this same issue again, for at least the past 30 days (my error logs don't go back before then). 

I wonder why the fix stopped working. I can try to PR making it work again, but I'm disturbed it broke despite a test committed that's supposed to ensure it's working. 

(Also don't understand why Facebook is messing up our URLs!)

**Comment by mejackreed** [comment]
Feel free to submit another PR and a test along side it please. Re: why Facebook is messing up our urls. My understanding is because of the PHP/Hack implementation that Facebook uses. I have submitted it as an issue to friends who work at Facebook in the past, but no resolution ever came up.

**Comment by jrochkind** [comment]
I can confirm I have been getting this error since April 21... I am not sure what version of BL I had deployed then, maybe that's when I first deployed BL 7, and 7 brought it back?

I'm afraid I'm running into my usual problem I have trying to contribute to Blacklight, which is I can't figure out how to get tests to run locally. Without that, I will have trouble making a failing test, or figuring out why the existing test is *not* failing even though the behavior it tests for is not happening. I'll keep working on it a bit, but may not be able to get there, sorry. :(
