### ISSUE TITLE
Locale switcher fails on search_history page

### ISSUE THREAD

**Issue by hackartisan** [projectblacklight/blacklight#1809]
After setting up locales as recommended in the rails guide on i18n, and implementing a dirt simple language picker, everything works great except the search history page, which gives the following error: https://gist.github.com/hackmastera/23597d7de9144607de3d71589de6bef4

here's the code for context: https://github.com/pulibrary/lae-blacklight/commit/0aede0fea4861f3690eccf036566a1dca38e14bf

another user experiencing the same problem: https://stackoverflow.com/questions/44965303/link-to-with-parameters-for-an-engine-route/47357046#47357046

If there is some way to change the routing that would accommodate this use case it would be great, since it's a logical extension of a supported blacklight use case (i18n).

@jrochkind on slack suggests following devise's example of injecting routes via a method call:
"the alternate is providing a method to generate routes into your main app. A method with parameters, that you can customize, or not call, etc. So it’s still extendable etc.  This is what devise does for instance, devise is not an ‘isolated’ engine, it just injects it’s routes into the main app, via method call. Ironically, Blacklight seems to have such methods to inject routes into your main app and is _also_ an isolated engine wrt to routing, possibly the worst of both worlds."

**Comment by jcoyne** [comment]
How about using `request.fullpath` and appending `?lang=en` or `&lang=es` as appropriate rather than relying on rails to build the route?

**Comment by hackmastera** [comment]
@jcoyne I don't think it would be a matter of simply appending; you'd have to do a regex. Sounds like that's what the stackoverflow poster ended up doing.

**Comment by jrochkind** [comment]
You can defintiely do a regexp. You've now hard-coded assumptions about how routing works (is it a query param, or in the path?), in ways that are non-ideal for Rails.  By design, and usually for most "regular" routes, you can generate paths in a way that is independent of how the actual URLs will look, so routing can make changes (like path component vs query param, or more complex path component implications) without the code that generates the paths having to change. 

The regexp hack may be the simplest/most feasible thing to do in the current context however. It's not hard to write that code, even though it's not simply appending and you have to do a regexp (or other state-based logic), it's not complex code to write, if you're willing to hard-code assumptions about how locale is represented in a URL.

**Comment by hackmastera** [comment]
Yes I ended up doing a regex because the c/p of the routes still left another route broken.

**Comment by barmintor** [comment]
Is this a Blacklight issue or a Rails issue?

**Comment by cbeer** [comment]
It seems to be working fine now, at least in the Blacklight demo app.
