### ISSUE TITLE
Why include `Blacklight::Controller` in ApplicationController?

### ISSUE THREAD

**Issue by jrochkind** [projectblacklight/blacklight#2095]
The [generator adds to your ApplicationController](https://github.com/projectblacklight/blacklight/blob/8b9041544553ce0dd0d979f9f39f78d94b30b46d/lib/generators/blacklight/controller_generator.rb#L16-L22):

```ruby
  # Adds a few additional behaviors into the application controller
  include Blacklight::Controller
  layout :determine_layout if respond_to? :layout
```

I have an app that has other controllers unrelated to Blacklight. I don't really want to inject Blacklight-specific behaviors in my ApplicationController effecting every controller in my app. I don't understand what these "few additional behaviors" are, or why Blacklight thinks I want/need them in every controller in my app. 

The comments at the top of [Blacklight::Controller](https://github.com/projectblacklight/blacklight/blob/8b9041544553ce0dd0d979f9f39f78d94b30b46d/app/controllers/concerns/blacklight/controller.rb) confirm that it was written being expected to be added to ApplicationController. 

But I don't totally get what's going on. Does anyone have any insight?

**Comment by barmintor** [comment]
You shouldn't have to worry about it in controllers that don't use Blacklight behaviors. That mixin sets up some BL helper methods and the configuration rigging.

**Comment by jrochkind** [comment]
Two years later I still think this is an unfortunate design, that Blacklight tries to insist on adding custom logic to your ApplicationController superclass and thus to every controller in your app, even those that have nothing to do with Blacklight behavior, and shouldn't need any BL helper methods or configuration rigging. I think it raises the potential for bugs, and encourages "everything depends on everything else" programming. 

But in my actual Blacklight app, i am not including `Blacklight::Controller` in the `ApplicationController`, I simply removed that line that was generated by Blacklight. 

It seems to be working fine. 

So for anyone coming to this later and wondering if you can get away with that -- so far so good for me. 

For Blacklight maintainers, I'd still recommend considering removing this line from generator. I could certainly make the PR myself, but I don't really have deep understanding of BL these days and don't understand how it may effect other BL apps or edge cases, or what the original intention (if any) of this was; I can just say that it works fine in my app.

**Comment by barmintor** [comment]
I see how I misunderstood your question 2 years ago - you were less interested in what was going on in the mixin than what was going on from a design perspective.

Based on [this commit from v3.0](https://github.com/projectblacklight/blacklight/commit/501f26f7d66459eaa910ba304248704f59dd2178), it seems like this design was an effort to ensure that the module methods were available to all of the Blacklight controllers. At the time, as you can see in that commit, there were 6 - I believe there are fewer now (it looks like 3, that's it's own archaeological expedition).

If you have added Blacklight to an existing application, you may not be using any of the other Blacklight controllers, and thus safely deleted that line (I have some applications like that myself, at least if I remember correctly). So if you were going to pursue developing a PR to change this part of the generator, one thing you would need to account for is the other controllers, and ensuring they continued to work (the generated app for tests should be good for demonstrating this). It may also be the case that the composition of the controller mixins could be revisited to make it clearer what was needed by a CatalogController-like controller, and what was necessary for SearchHistoryController - obviously that would be more than a simple deletion.

Another issue to contend with in your PR would be what the goals of the generators are - from what I can see, they are written from the perspective of setting up Blacklight on a new Rails app. As your own work suggests, maintainers of existing apps that are folding Blacklight in might be expected to navigate the generator code to see how to make the necessary adjustments - but I don't think it's clear in the documentation. From that perspective, this ticket may be for better documentation, but that too is far from a one-line change.

Your PR might also recommend additional options to the generators as a compromise between approaching this issue as an application design issue or a documentation issue. In my experience, the quick start guides (that is, the installation instructions) generate a lot of questions, especially from folks new to Rails (or web development generally), so that approach would have its own documentation considerations.

Without too much reflection, it also seems like there's an interesting version-numbering consideration here - it would be tricky to deprecate this behavior in a way that Rails would report, which (speaking here for myself) is something I have really appreciated from Blacklight committers in the past.

In any case, there's a surprising amount to think about around changing this - I'm interested to see the proposal!
