### ISSUE TITLE
It's not possible to click on a facet value

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#2142]
Using Firefox 69, the new stretched-link value is overlaying the whole card, not just the header, which makes facet values (e.g. "Book") impossible to click.

I think we should revert #2132 or look at one of the solutions here: https://getbootstrap.com/docs/4.3/utilities/stretched-link/#identifying-the-containing-block

@cdmo I'd like your thoughts.

**Comment by cdmo** [comment]
@jcoyne I will take another look at this today, but, what I was seeing is that the stretched-link was causing a different problem - the link click was jumping the page down. Which is why I put in this [PR](https://github.com/projectblacklight/blacklight/pull/2137)

I see you've done some PRs too, so I'll take a look. If nothing else though a test added for the window not jumping would be good.

**Comment by cdmo** [comment]
Just to add here too, basically I think I'm advocating for a heading3 that doesn't have any listener on it (i.e., the collapse classes) and then replace the anchor with a button. This means no new javascript and (if I'm right about it being extraneous) removing existing javascript ([collapse.js](https://github.com/projectblacklight/blacklight/blob/ce1770521f7cf6d4269286a4e9922f6f731a0960/app/javascript/blacklight/collapsable.js))
