### ISSUE TITLE
Facet queries are not passed through without adding a facet field

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/blacklight#2401]
My guess is this was introduced around #2371. Previously, facet queries could be used by the application without having to explicitly define it.

For example: 

`http://127.0.0.1:3000/catalog?f%5Bdc_source_sm%5D%5B%5D=princeton-1r66j405w` would filter results, without `dc_source_sm` being defined. See failing test `search_spec` https://app.circleci.com/pipelines/github/geoblacklight/geoblacklight/663/workflows/4a2ddcea-9ab2-401f-8c95-485969930c93/jobs/4878

**Comment by dkinzer** [comment]
Just my two cents, but I think the current behavior is the correct behavior.  In fact, I have an open ticket from way back when trying to make it act like this: #1989 .  I explain it in the ticket but the gist of it is that it helps prevent sending facets defined for a controller when the facet is in the URL parameter actually there for another controller.

At Temple we run into this a lot because we have 4 different search controllers all potentially adding facet parameters to the URL that should not be acted upon by all the search controllers.

I also have a related ticket at projectblacklight/blacklight_range_limit#169.

**Comment by barmintor** [comment]
Closing as this is now the specced behavior.
