### ISSUE TITLE
Search results pages throw error Psych::DisallowedClass (Tried to load unspecified class: ActiveSupport::HashWithIndifferentAccess)

### ISSUE THREAD

**Issue by seanaery** [projectblacklight/blacklight#2768]
With a patch for [CVE-2022-32224](https://discuss.rubyonrails.org/t/cve-2022-32224-possible-rce-escalation-bug-with-serialized-columns-in-active-record/81017) in place (e.g., an update to Rails 6.1.6.1), we are now seeing Blacklight 7 search results pages yield the following error (example):
```
app_1         | Processing by CatalogController#index as HTML
app_1         |   Parameters: {"utf8"=>"✓", "group"=>"true", "search_field"=>"all_fields", "q"=>"car"}
app_1         | Completed 500 Internal Server Error in 5ms (ActiveRecord: 0.0ms | Allocations: 13651)
app_1         | 
app_1         | 
app_1         |   
app_1         | Psych::DisallowedClass (Tried to load unspecified class: ActiveSupport::HashWithIndifferentAccess):
app_1         |   
app_1         | /usr/local/lib/ruby/2.7.0/psych/class_loader.rb:97:in `find'
app_1         | /usr/local/lib/ruby/2.7.0/psych/class_loader.rb:28:in `load'
```
It seems that a `HashWithIndifferentAccess` is not permitted and ActiveRecord needs explicit configuration in order to allow it, e.g.:
```
config.active_record.yaml_column_permitted_classes = [Symbol, Date, Time, Hash, HashWithIndifferentAccess]
```

**Comment by jrochkind** [comment]
@barmintor pointed out this is triggered here: https://github.com/projectblacklight/blacklight/blob/release-7.x/app/models/search.rb#L6

It's too bad the Rails patch allows you to _serialize_ this to DB, but only fails when you try to load it again. 

One fix might involve making sure a HashWithIndifferentAccess isn't actually saved to that column, it's first converted to an ordinary Hash. But that wouldn't help with existing apps with existing data in the db (although in many apps this is transitory data that can be deleted, so). 

@seanaery I'm curious about the other classes in your list: `[Symbol, Date, Time, Hash, HashWithIndifferentAccess]` -- did you add those others because you found they were actually necessary in your app, are Symbo, Date, and Time actually going in there?

**Comment by jrochkind** [comment]
In my own app, this monkey-patch to blacklight's `Search` class is sufficient for my app to pass tests again. 

```ruby
        def query_params=(val)
          super(val.to_hash)
        end
```

But in an actually deployed app you'd still have some things in the database that used HashWithIndiffernetAccess, so that would still be a problem. 

In my own app, I think I can actually just delete the whole `Search` table -- Unless you are using "saved search" feature (did someone actually remove that from BL? I forget), these are temporary records anyway only used for "search context", I don't mind if users "in media res" at the point of deployment lose their search context. 

I'm not sure about a universal solution though. That "Search" model/table is really kind of messy and I wish we didn't have it at all.

**Comment by jrochkind** [comment]
@barmintor I'm not sure what you mean, but note my example used `to_hash` not `to_h`. It seems to me to work just fine with symbol keys. 

Wait, do you want to READ the key as symbol on the way out?  Yeah, there's no way to do that. Unless you really serialize/deserialize a hash with indiffernet access.

**Comment by jrochkind** [comment]
@barmintor points out, what if you want to be able to do (and blacklight code may assume it can do):

```ruby
search.query_params = {foo: "bar"}
```

You'd still run into the problem, but this time the YAML.safe_load complaining about the `Symbol` rather than the `HashWithIndifferentAccess`. 

OK, it's ugly, but this is one way to get all keys normalized from Symbols to Strings, in an ordinary `Hash`, whether you pass in an ordinary Hash or a HWIA:

```ruby
def query_params=(v)
   super(v.to_hash.with_indifferent_access.to_hash)
end
```

**Comment by seanaery** [comment]
> curious about the other classes in your list...
@jrochkind Thanks for pointing that out --  I should note that the other classes I listed (besides `HashWithIndifferentAccess`) were somewhat arbitrary and I didn't look closely at whether my apps actually need to account for them. I don't know if un-permitting any of the [default deserializable classes](https://www.rubydoc.info/stdlib/psych/Psych.safe_load) would have any ill effects anywhere, but maybe `HashWithIndifferentAccess` on its own is sufficient.
