### ISSUE TITLE
Propshaft generator is running even when importmap is installed.

### ISSUE THREAD

**Issue by jcoyne** [projectblacklight/blacklight#3248]
This is causing the spec/features/bookmark_spec.rb to fail because the javascript is broken because `blacklight-frontend` is not in the importmap.

The lines that cause the problem are here:
https://github.com/projectblacklight/blacklight/blob/main/lib/generators/blacklight/assets/propshaft_generator.rb#L27-L28

**Comment by thatbudakguy** [comment]
Is this because the asset generator only cares about whether Propshaft is installed? This behavior confused me in Geoblacklight, where we use both propshaft and Importmaps, but because of the order here, only the Propshaft generator runs and I had to handle the Importmap stuff manually:
https://github.com/projectblacklight/blacklight/blob/2e95685368c516dedee952978ead6012a4866ffb/lib/generators/blacklight/assets_generator.rb#L10-L16

**Comment by thatbudakguy** [comment]
It seems to me like that logic should be adjusted so that Propshaft and Sprockets are mutually exclusive, but Importmaps is unrelated to the presence of the other two.

**Comment by jcoyne** [comment]
I think https://github.com/projectblacklight/blacklight/pull/3340 fixes this issue.

**Comment by jrochkind** [comment]
I am btw considering and experimenting with: what if we changed the importmap to be to package `blacklight-frontend`, so importmap-rails things did `import "blacklight-frontend"` instead of `import "blacklight"` too?

The advantage would be that importmap-rails apps and NPM-package-using apps (jsbundling-rails, vite, etc) could now have _identical_ javascript source files.  

The only difference is that under importmaps-rails, the importmaps would connect `import "blacklight-frontned"` to certain URLs, and under npm-package-builder apps, the builder would connect `import "blacklight-frontend"` to the same code via the npm package.  All ESM JS, all equivalent, just a question of how the import gets connected to a file -- which I think is the intention of importmaps, to be able to switch back and forth like this without having to change your source even. 

I think it could make maintanence of our generators easier too, if the JS source files for all (non legacy sprockets) paths were actually the same, instead of calling the path `blacklight` in some and `blacklight-frontend` in others. 

(This all comes about because `blacklight` was already taken in npm of course!)

Just thought I'd mention one of my current investigations, since your comments were relevant to it.  In this possible path, `blacklight-frontend` _would_ be in the importmap!
